---
- name: Install SeaweedFS
  hosts: seaweedfs
  become: true
  remote_user: root

  vars_files:
    - "vars/secrets.yml"

  roles:
    - zorlin.netbird
    - seaweedfs

- name: Set up SeaweedFS Masters
  hosts: seaweedfs_masters
  become: true
  remote_user: root

  vars_files:
    - "vars/secrets.yml"
    - "vars/seaweedfs.yml"

  roles:
    - seaweedfs-master

- name: Set up CockroachDB
  hosts: cockroachdb
  become: true
  remote_user: root

  vars:
    - cockroachdb_initialize: true

  roles:
    - cockroachdb

- name: Set up SeaweedFS Filers
  hosts: seaweedfs_filers
  become: true
  remote_user: root

  vars_files:
    - "vars/secrets.yml"
    - "vars/seaweedfs.yml"

  roles:
    - haproxy
    - seaweedfs-filer

- name: Set up SeaweedFS Volume Servers
  hosts: seaweedfs_volume_servers
  become: true
  remote_user: root

  vars_files:
    - "vars/secrets.yml"
    - "vars/seaweedfs.yml"

  roles:
    - seaweedfs-volume-server