---
- name: Install SeaweedFS
  hosts: seaweedfs
  become: true
  remote_user: root

  vars_files:
    - "vars/secrets.yml"

  roles:
    - zorlin.netbird
    - seaweedfs

- name: Set up SeaweedFS Masters
  hosts: seaweedfs_masters
  become: true
  remote_user: root

  vars_files:
    - "vars/secrets.yml"
    - "vars/seaweedfs.yml"

  roles:
    - seaweedfs-master

- name: Set up CockroachDB
  hosts: cockroachdb
  become: true
  remote_user: root

  vars:
    - cockroachdb_initialize: false

  roles:
    - cockroachdb

- name: Set up SeaweedFS Filers
  hosts: seaweedfs_filers
  become: true
  remote_user: root

  vars_files:
    - "vars/secrets.yml"
    - "vars/seaweedfs.yml"

  roles:
    - haproxy
    - seaweedfs-filer

- name: Set up SeaweedFS Volume Servers
  hosts: seaweedfs_volume_servers
  become: true
  remote_user: root

  vars_files:
    - "vars/secrets.yml"
    - "vars/seaweedfs.yml"

  roles:
    - seaweedfs-volume-server

- name: Set up SeaweedFS Mounts
  hosts: whypfs_nodes
  become: true
  remote_user: root

  tasks:
    - name: Make SeaweedFS mount point
      file:
        path: /mnt/seaweedfs
        owner: root
        group: root
        mode: 0755
        state: directory

    - name: Set up SeaweedFS mount
      template:
        src: mnt-seaweedfs.mount.j2
        dest: /etc/systemd/system/mnt-seaweedfs.mount
        owner: root
        group: root
        mode: 0755

    - name: Enable SeaweedFS mount
      systemd:
        name: mnt-seaweedfs.mount
        enabled: true
        state: started
        daemon_reload: true
      ignore_errors: true
      failed_when: false
