---
- name: Install SeaweedFS
  hosts: seaweedfs
  become: true
  remote_user: root

  vars_files:
    - "vars/secrets.yml"

  roles:
    - zorlin.netbird
    - seaweedfs

- name: Set up SeaweedFS Masters
  hosts: seaweedfs_masters
  become: true
  remote_user: root

  vars_files:
    - "vars/secrets.yml"
    - "vars/seaweedfs.yml"

  roles:
    - seaweedfs-master

- name: Set up CockroachDB
  hosts: cockroachdb
  become: true
  remote_user: root

  vars:
    - cockroachdb_initialize: true

  roles:
    - cockroachdb

- name: Set up SeaweedFS Filers
  hosts: seaweedfs_filers
  become: true
  remote_user: root

  vars_files:
    - "vars/secrets.yml"
    - "vars/seaweedfs.yml"

  roles:
    - haproxy
    - seaweedfs-filer

- name: Set up SeaweedFS Volume Servers
  hosts: seaweedfs_volume_servers
  become: true
  remote_user: root

  vars_files:
    - "vars/secrets.yml"
    - "vars/seaweedfs.yml"

  roles:
    - seaweedfs-volume-server

- name: Set up SeaweedFS Mounts
  hosts: whypfs_nodes
  become: true
  remote_user: root

  tasks:
    - name: Make SeaweedFS mount point
      file:
        path: /mnt/seaweedfs
        owner: root
        group: root
        mode: 0755
        state: directory

    - name: Set up SeaweedFS mount
      mount:
        path: /mnt/seaweedfs
        src: fuse
        fstype: fuse.weed
        state: mounted
        opts:
          - filer.path=/estuary
          - filer='{% for node in groups.seaweedfs_filers | intersect(groups[seaweedfs_region]) %}{{ hostvars[node]["ansible_wt0"]["ipv4"]["address"] }}:8888{% if not loop.last %},{% endif %}{% endfor %}'
