---
- name: Install prerequisites
  ansible.builtin.package:
    name:
      - git
      - build-essential

- name: Check out WhyPFS
  ansible.builtin.git:
    repo: https://github.com/zorlin/whypfs
    version: master
    dest: /usr/local/src/whypfs

- name: Build WhyPFS
  ansible.builtin.shell:
    cmd: '. /etc/profile.d/golang.sh ; go build'
    chdir: /usr/local/src/whypfs
    creates: /usr/local/src/whypfs/whypfs
